// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD-U1avjTaZ6vL3Uk5U9xY_J6iFSxenpc',
    appId: '1:304194811490:web:e396e6fd38a5223785c33b',
    messagingSenderId: '304194811490',
    projectId: 'blog-app-235fb',
    authDomain: 'blog-app-235fb.firebaseapp.com',
    storageBucket: 'blog-app-235fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa6ixqsyOCGk6Y6RtPryzDt1nKtmnNtlA',
    appId: '1:304194811490:android:a573e8e98fd43eb085c33b',
    messagingSenderId: '304194811490',
    projectId: 'blog-app-235fb',
    storageBucket: 'blog-app-235fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn50m060le8XhpGkOw3hhgRxgZPN4X62M',
    appId: '1:304194811490:ios:8fafcdd22ed1430685c33b',
    messagingSenderId: '304194811490',
    projectId: 'blog-app-235fb',
    storageBucket: 'blog-app-235fb.appspot.com',
    iosClientId: '304194811490-97tq1egqnfkn3v8cskhols21pnh2ko5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );
}
